version: '3.7'

services:
  react-admin:
    container_name: '57'
    image: wiezmankimchi/react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3057:3000"
    environment:
      - NODE_ENV=development  